# Generated by Django 4.1.3 on 2024-09-29 23:42

import aimtravel_site.user_auth.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Потребителски профил', 'verbose_name_plural': 'Потребителски профили'},
        ),
        migrations.AddField(
            model_name='appuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='user-slug', editable=False, populate_from=aimtravel_site.user_auth.models.generate_slug),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_picture',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to='user/pictures/', verbose_name='Профилна снимка'),
        ),
    ]
