# Generated by Django 4.1.3 on 2024-01-06 21:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Потребителски профил', 'verbose_name_plural': 'Потребителски профили'},
        ),
        migrations.AddField(
            model_name='appuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='first_name', unique=True),
            preserve_default=False,
        ),
    ]
