# Generated by Django 4.1.3 on 2024-09-30 00:06

import aimtravel_site.user_auth.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_appuser_options_appuser_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=aimtravel_site.user_auth.models.generate_slug, unique=True),
        ),
    ]
