# Generated by Django 4.1.3 on 2024-01-09 20:57

import aimtravel_site.user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_appuser_options_appuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_picture',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to=aimtravel_site.user_auth.models.upload_to_path, verbose_name='Профилна снимка'),
        ),
    ]
