# Generated by Django 4.1.3 on 2024-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_appuser_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_picture',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to='user/pictures/', verbose_name='Профилна снимка'),
        ),
    ]
