# Generated by Django 4.1.3 on 2024-09-29 23:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_appuser_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='first_name'),
        ),
    ]
