# Generated by Django 4.1.3 on 2024-01-09 20:46

import aimtravel_site.taxes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('family_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mothers_maiden_name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('how_did_you_find_us', models.CharField(blank=True, choices=[('friends', 'friends'), ('brochure', 'brochure'), ('internet', 'internet'), ('posters', 'posters'), ('agency', 'agency')], max_length=15, null=True)),
                ('social_security', models.CharField(blank=True, max_length=12, null=True)),
                ('working_year', models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4, null=True)),
                ('arrival_date_in_usa', models.DateField(blank=True, null=True)),
                ('departure_date_in_usa', models.DateField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, choices=[('J1', 'J1'), ('J2', 'J2'), ('F1', 'F1'), ('F2', 'F2'), ('Green card', 'Green Card'), ('H1B', 'H1B'), ('H2B', 'H2B'), ('M', 'M'), ('Other', 'Other'), ('None', 'None')], max_length=10, null=True)),
                ('program_type', models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Work and Travel', 'Work and Travel'), ('Career Training', 'Career Training'), ('Other', 'Other'), ('None', 'None')], max_length=20, null=True)),
                ('previous_tax_declarations', models.BooleanField(default=False)),
                ('visa_changing', models.BooleanField(default=False)),
                ('pin_from_irs', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=40, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_city', models.CharField(blank=True, max_length=30, null=True)),
                ('company_state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, null=True)),
                ('company_zip', models.CharField(blank=True, max_length=6, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_fax', models.CharField(blank=True, max_length=15, null=True)),
                ('company_email', models.CharField(blank=True, max_length=50, null=True)),
                ('last_paycheck', models.BooleanField(default=False)),
                ('w_2', models.BooleanField(default=False)),
                ('american_bank_account', models.BooleanField(default=False)),
                ('type_of_account', models.CharField(blank=True, choices=[('Checking', 'Checking'), ('Saving', 'Saving')], max_length=8, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на паспорт')),
                ('visa_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на виза')),
                ('ssn_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на Social Security')),
                ('last_paycheck_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последни чекове')),
                ('w2_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='W-2 форми')),
                ('bank_account_screenshot', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Screenshot на банковата ти сметка,потвържващ че ти си собственик на сметката')),
                ('us_document_copy', models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Снимка на ID от САЩ/Американска Шофьорска книжка (само ако имате)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax-Refund',
                'verbose_name_plural': 'Taxes',
            },
        ),
    ]
