# Generated by Django 4.1.3 on 2024-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='status',
            field=models.CharField(choices=[('Попълване на документи', 'Попълване на документи'), ('В процес на обработка', 'В процес на обработка'), ('В очакване на отговор', 'В очакване на отговор'), ('В очакване на плащане', 'В очакване на плащане'), ('Завършен', 'Завършен')], default='Попълване на документи', max_length=30),
        ),
    ]
