# Generated by Django 4.1.3 on 2024-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='status',
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_attached_docs',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_declaration_in_progress',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_declaration_submitted',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_federal_customer',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_federal_in',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_pers_dat',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_reg',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_signed_c',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_state_customer',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_state_in',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_tax_paid',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_waiting_federal',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_waiting_state',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='Червено', max_length=10, null=True),
        ),
    ]
