# Generated by Django 4.1.3 on 2024-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_remove_taxes_status_taxes_stat_attached_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='stat_attached_docs',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='stat_declaration_in_progress',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='stat_signed_c',
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_docs',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_in_progress',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_declaration_submitted',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_federal_customer',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_federal_in',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_pers_dat',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_reg',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='3', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_state_customer',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_state_in',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_tax_paid',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_waiting_federal',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_waiting_state',
            field=models.CharField(blank=True, choices=[('1', 'Червено'), ('2', 'Жълто'), ('3', 'Зелено')], default='1', max_length=10, null=True),
        ),
    ]
