# Generated by Django 4.1.3 on 2024-01-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_remove_taxes_stat_attached_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='stat_federal_in',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='stat_state_in',
        ),
    ]
