# Generated by Django 4.1.3 on 2024-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_remove_taxes_stat_federal_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='american_bank_account',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='last_paycheck',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='pin_from_irs',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='previous_tax_declarations',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='visa_changing',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='w_2',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
    ]
