# Generated by Django 4.1.3 on 2024-01-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0006_alter_taxes_american_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='last_paycheck_copy',
            new_name='last_paycheck_w2',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='w2_copy',
        ),
    ]
