# Generated by Django 4.1.3 on 2024-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0007_rename_last_paycheck_copy_taxes_last_paycheck_w2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='last_paycheck_w2_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxes',
            name='passport_copy_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxes',
            name='ssn_copy_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxes',
            name='visa_copy_used',
            field=models.BooleanField(default=False),
        ),
    ]
