# Generated by Django 4.1.3 on 2024-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0008_taxes_last_paycheck_w2_used_taxes_passport_copy_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='bank_account_screenshot_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxes',
            name='us_document_copy_used',
            field=models.BooleanField(default=False),
        ),
    ]
