# Generated by Django 4.1.3 on 2024-02-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0009_taxes_bank_account_screenshot_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='family_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_declaration_submitted',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_docs',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_federal_customer',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_in_progress',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_pers_dat',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_reg',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='3', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_state_customer',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_tax_paid',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_waiting_federal',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='stat_waiting_state',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
    ]
