# Generated by Django 4.1.3 on 2024-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0010_taxes_family_name_en_taxes_first_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='how_did_you_find_us',
        ),
        migrations.AddField(
            model_name='taxes',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
