# Generated by Django 4.1.3 on 2024-02-07 15:02

import aimtravel_site.taxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0011_remove_taxes_how_did_you_find_us_taxes_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='stat_tax_paid',
            new_name='stat_tax_paid_federal',
        ),
        migrations.AddField(
            model_name='taxes',
            name='signed_and_scanned_contract',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Подписан и сканиран договор'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_tax_paid_state',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
    ]
