# Generated by Django 4.1.3 on 2024-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0012_rename_stat_tax_paid_taxes_stat_tax_paid_federal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='signed_and_scanned_contract_used',
            field=models.BooleanField(default=False),
        ),
    ]
