# Generated by Django 4.1.3 on 2024-02-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0013_taxes_signed_and_scanned_contract_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='federal_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='fee_federal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='fee_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='general_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='state_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='waiting_docs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
