# Generated by Django 4.1.3 on 2024-02-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0014_taxes_federal_amount_taxes_fee_federal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='stat_federal_fee_paid',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='stat_state_fee_paid',
            field=models.CharField(blank=True, choices=[('1', 'Начало'), ('2', 'В прогрес'), ('3', 'Готово')], default='1', max_length=10, null=True),
        ),
    ]
