# Generated by Django 4.1.3 on 2024-02-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0015_taxes_stat_federal_fee_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='federal_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='fee_federal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='fee_state',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='state_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
