# Generated by Django 4.1.3 on 2024-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0016_alter_taxes_federal_amount_alter_taxes_fee_federal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
