# Generated by Django 4.1.3 on 2024-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0017_taxes_step_alter_taxes_is_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxes',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='taxes',
            name='attachments_info_done',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='bank_info_done',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='employer_info_done',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='personal_info_done',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='travel_info_done',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
    ]
