# Generated by Django 4.1.3 on 2024-03-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0018_alter_taxes_options_taxes_attachments_info_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='stat_tax_paid_federal',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='stat_tax_paid_state',
        ),
        migrations.AddField(
            model_name='taxes',
            name='sign',
            field=models.ImageField(blank=True, default='static/img/sign.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='federal_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='general_status',
            field=models.CharField(blank=True, choices=[('registration', 'Регистрация'), ('declaration', 'Подадена декларация'), ('federal', 'Пристигнал Federal'), ('state', 'Пристигнал State'), ('federalfee', 'Платена комисионна Federal'), ('statefee', 'Платена комисионна State'), ('allpaid', 'Комисионна платена')], default='registration', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='state_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
