# Generated by Django 4.1.3 on 2024-03-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0019_remove_taxes_stat_tax_paid_federal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='sign',
        ),
    ]
