# Generated by Django 4.1.3 on 2024-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0020_remove_taxes_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='sign',
            field=models.ImageField(blank=True, default='C:\\Users\\vlzah\\Documents\\PyCharm Projects\\aimtravel_site_repo\\static\\img\\sign.png', upload_to=''),
        ),
    ]
