# Generated by Django 4.1.3 on 2024-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0021_taxes_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='sign',
        ),
    ]
