# Generated by Django 4.1.3 on 2024-09-15 20:56

import aimtravel_site.taxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0022_remove_taxes_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='last_paycheck_w2_used',
            new_name='last_paycheck_used',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='last_paycheck_w2',
        ),
        migrations.AddField(
            model_name='taxes',
            name='w2_form',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='W2 форма'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='w2_form_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='last_paycheck',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последни чекове'),
        ),
    ]
