# Generated by Django 4.1.3 on 2024-09-15 21:25

import aimtravel_site.taxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0023_rename_last_paycheck_w2_used_taxes_last_paycheck_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='last_paycheck_used',
            new_name='last_paycheck_doc_used',
        ),
        migrations.AddField(
            model_name='taxes',
            name='last_paycheck_doc',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последни чекове'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='last_paycheck',
            field=models.CharField(blank=True, choices=[('No', 'Не'), ('Yes', 'Да')], max_length=3, null=True),
        ),
    ]
