# Generated by Django 4.1.3 on 2024-09-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0024_rename_last_paycheck_used_taxes_last_paycheck_doc_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='working_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4, null=True),
        ),
    ]
