# Generated by Django 4.1.3 on 2024-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0025_alter_taxes_working_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='working_year',
            field=models.CharField(blank=True, choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020')], max_length=4, null=True),
        ),
    ]
