# Generated by Django 4.1.3 on 2024-09-27 21:30

import aimtravel_site.taxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0026_alter_taxes_working_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='w2_lpc_e3',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последен чек/W2 (работодател 3)'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='w2_lpc_e3_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxes',
            name='w2_lpc_e4',
            field=models.FileField(blank=True, null=True, upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последен чек/W2 (работодател 4)'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='w2_lpc_e4_used',
            field=models.BooleanField(default=False),
        ),
    ]
