# Generated by Django 4.1.3 on 2024-09-27 22:04

import aimtravel_site.taxes.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0027_taxes_w2_lpc_e3_taxes_w2_lpc_e3_used_taxes_w2_lpc_e4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='bank_account_screenshot',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Screenshot на банковата ти сметка,потвържващ че ти си собственик на сметката'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='last_paycheck_doc',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последни чекове'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='passport_copy',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на паспорт'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='signed_and_scanned_contract',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Подписан и сканиран договор'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='ssn_copy',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на Social Security'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='us_document_copy',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Снимка на ID от САЩ/Американска Шофьорска книжка (само ако имате)'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='visa_copy',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Копие на виза'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='w2_form',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='W2 форма'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='w2_lpc_e3',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последен чек/W2 (работодател 3)'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='w2_lpc_e4',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path, verbose_name='Последен чек/W2 (работодател 4)'),
        ),
    ]
