# Generated by Django 4.1.3 on 2024-09-27 22:47

import aimtravel_site.taxes.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0028_alter_taxes_bank_account_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='signed_and_scanned_contract',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=aimtravel_site.taxes.models.upload_to_path),
        ),
    ]
