# Generated by Django 4.1.3 on 2025-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0030_alter_taxes_signed_and_scanned_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='working_year',
            field=models.CharField(blank=True, choices=[('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021')], max_length=4, null=True),
        ),
    ]
