# Generated by Django 4.1.3 on 2023-08-21 08:39

import aimtravel_site.web.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид услуга')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание на услугата')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Цена на услугата')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Град')),
                ('fact1', models.TextField(blank=True, null=True, verbose_name='Факт 1')),
                ('fact2', models.TextField(blank=True, null=True, verbose_name='Факт 2')),
                ('fact3', models.TextField(blank=True, null=True, verbose_name='Факт 3')),
                ('city_pic', models.ImageField(blank=True, null=True, upload_to='city_pics/', verbose_name='Снимка')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=30, null=True, verbose_name='Работодател')),
                ('employer_city', models.CharField(max_length=20, null=True, verbose_name='Град')),
                ('employer_state', models.CharField(max_length=2, null=True, verbose_name='Щат')),
                ('employer_history', models.TextField(max_length=250, null=True, verbose_name='Кратка история')),
                ('employer_photo', models.URLField(blank=True, null=True, verbose_name='Снимка-URL')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Оферта')),
                ('student_name_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 1')),
                ('student_pic_1', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 1')),
                ('feedback_1', models.TextField(blank=True, null=True, verbose_name='Отзив 1')),
                ('student_name_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 2')),
                ('student_pic_2', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 2')),
                ('feedback_2', models.TextField(blank=True, null=True, verbose_name='Отзив 2')),
                ('student_name_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 3')),
                ('student_pic_3', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 3')),
                ('feedback_3', models.TextField(blank=True, null=True, verbose_name='Отзив 3')),
                ('student_name_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 4')),
                ('student_pic_4', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 4')),
                ('feedback_4', models.TextField(blank=True, null=True, verbose_name='Отзив 4')),
                ('student_name_5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 5')),
                ('student_pic_5', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 5')),
                ('feedback_5', models.TextField(blank=True, null=True, verbose_name='Отзив 5')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(blank=True, choices=[('Self Arranged', 'Self Arranged'), ('Full Placement Standard', 'Full Placement Standard'), ('Premium Full Placement', 'Premium Full Placement')], default='Full Placement Standard', max_length=25, null=True, verbose_name='Ценови план:')),
                ('price', models.FloatField(verbose_name='Цена:')),
                ('price_description', models.TextField(blank=True, help_text='Моля добавете описание', null=True, verbose_name='В цената е включено:')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Име на работодател')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='Щат')),
                ('job_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Работна позиция')),
                ('wage', models.FloatField(blank=True, null=True, verbose_name='Заплащане')),
                ('tips', models.BooleanField(blank=True, null=True, verbose_name='Бакшиши')),
                ('bonus', models.BooleanField(blank=True, null=True, verbose_name='Бонус')),
                ('minimum_hours', models.FloatField(blank=True, null=True, verbose_name='Минимум часове на седмица')),
                ('overtime', models.BooleanField(blank=True, null=True, verbose_name='Overtime')),
                ('housing', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Housing')),
                ('english_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ниво на английски език')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Стартова дата')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Крайна дата')),
                ('groups', models.BooleanField(blank=True, null=True, verbose_name='Подходящо за групи')),
                ('couples', models.BooleanField(blank=True, null=True, verbose_name='Подходящо за двойки')),
                ('suitable_for', models.CharField(blank=True, choices=[('Студенти', 'Студенти'), ('Нестуденти', 'Нестуденти')], max_length=20, null=True, verbose_name='Подходящо за')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Описание на работата')),
                ('offer_pic', models.ImageField(blank=True, null=True, upload_to='job_offer_pics/', verbose_name='Снимка')),
                ('ranking', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[aimtravel_site.web.validators.max_value])),
                ('new_offer', models.BooleanField(blank=True, null=True, verbose_name='Нова оферта')),
                ('sold_out_offer', models.BooleanField(blank=True, null=True, verbose_name='Sold out')),
                ('last_seats', models.BooleanField(blank=True, null=True, verbose_name='Последни места')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city', to_field='name')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.feedback', to_field='feedback_name')),
            ],
        ),
    ]
