# Generated by Django 4.1.3 on 2023-12-26 19:19

import aimtravel_site.web.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид услуга')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание на услугата')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Цена на услугата')),
            ],
            options={
                'verbose_name': 'Допълнителни услуги',
                'verbose_name_plural': 'Допълнителни услуги',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Град')),
                ('state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=20, null=True, verbose_name='Щат')),
                ('fact1', models.TextField(blank=True, null=True, verbose_name='Факт 1')),
                ('fact2', models.TextField(blank=True, null=True, verbose_name='Факт 2')),
                ('fact3', models.TextField(blank=True, null=True, verbose_name='Факт 3')),
                ('city_pic', models.ImageField(blank=True, null=True, upload_to='city_pics/', verbose_name='Снимка')),
            ],
            options={
                'verbose_name': 'Град',
                'verbose_name_plural': 'Градове',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=30, null=True, verbose_name='Работодател')),
                ('employer_city', models.CharField(max_length=20, null=True, verbose_name='Град')),
                ('employer_state', models.CharField(max_length=2, null=True, verbose_name='Щат')),
                ('employer_history', models.TextField(max_length=250, null=True, verbose_name='Кратка история')),
                ('employer_photo', models.URLField(blank=True, null=True, verbose_name='Снимка-URL')),
            ],
            options={
                'verbose_name': 'Работодател',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Оферта')),
                ('student_name_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 1')),
                ('student_pic_1', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 1')),
                ('feedback_1', models.TextField(blank=True, null=True, verbose_name='Отзив 1')),
                ('student_name_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 2')),
                ('student_pic_2', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 2')),
                ('feedback_2', models.TextField(blank=True, null=True, verbose_name='Отзив 2')),
                ('student_name_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 3')),
                ('student_pic_3', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 3')),
                ('feedback_3', models.TextField(blank=True, null=True, verbose_name='Отзив 3')),
            ],
            options={
                'verbose_name': 'Обратна връзка',
                'verbose_name_plural': 'Обратна връзка',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_self_arrange', models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Self Arranged:')),
                ('discounted_self_arrange', models.FloatField(blank=True, null=True, verbose_name='Промо цена за Self Arranged(задраскана):')),
                ('actual_standard', models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Full Standard:')),
                ('discounted_standard', models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Standard(задраскана):')),
                ('actual_premium', models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Full Premium:')),
                ('discounted_premium', models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Premium(задраскана):')),
                ('sevis', models.FloatField(blank=True, null=True, verbose_name='Такса Sevis:')),
                ('visa_interview', models.FloatField(blank=True, null=True, verbose_name='Такса визово интервю:')),
                ('plane_ticket_lowest', models.FloatField(blank=True, null=True, verbose_name='Самолетен билет - най-ниска цена:')),
                ('plane_ticket_highest', models.FloatField(blank=True, null=True, verbose_name='Самолетен билет - най-висока цена:')),
                ('sign_up_fees', models.FloatField(blank=True, null=True, verbose_name='Такса при записване:')),
                ('validity_date_day', models.IntegerField(blank=True, null=True, verbose_name='Валидно до - Ден:')),
                ('validity_date_month', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]*$', 'Използвай само главни букви.')], verbose_name='Валидно до - Месец:')),
                ('validity_date_year', models.IntegerField(blank=True, null=True, verbose_name='Валидно до - Година:')),
                ('amount_of_discount', models.IntegerField(blank=True, null=True, verbose_name='Отстъпка до ($):')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цени',
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Име на работодател')),
                ('job_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Работна позиция')),
                ('wage', models.FloatField(blank=True, null=True, verbose_name='Заплащане')),
                ('tips', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Бакшиши')),
                ('bonus', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Бонус')),
                ('minimum_hours', models.FloatField(blank=True, null=True, verbose_name='Минимум часове на седмица')),
                ('overtime', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Overtime')),
                ('housing', models.CharField(blank=True, default='Не', max_length=10, null=True, verbose_name='Housing')),
                ('english_level', models.CharField(blank=True, choices=[('Ниско', 'Ниско'), ('Средно', 'Средно'), ('Високо', 'Високо')], max_length=10, null=True, verbose_name='Ниво на английски език')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Най-ранно заминаване')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Най-късно заминаване')),
                ('groups', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Подходящо за групи')),
                ('couples', models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Подходящо за двойки')),
                ('suitable_for', models.CharField(blank=True, choices=[('Студенти', 'Студенти'), ('Нестуденти', 'Нестуденти')], max_length=20, null=True, verbose_name='Подходящо за')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Описание на работата')),
                ('offer_pic', models.ImageField(blank=True, null=True, upload_to='job_offer_pics/', verbose_name='Снимка')),
                ('ranking', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[aimtravel_site.web.validators.max_value])),
                ('new_offer', models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Нова оферта')),
                ('sold_out_offer', models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Sold out')),
                ('last_seats', models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Последни места')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city', to_field='name')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.feedback', to_field='feedback_name')),
            ],
            options={
                'verbose_name': 'Работна оферта',
                'verbose_name_plural': 'Работни оферти',
            },
        ),
    ]
