# Generated by Django 4.1.3 on 2023-08-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='students_feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=20, null=True)),
                ('student_pic', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзив')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.joboffer')),
            ],
        ),
    ]
