# Generated by Django 4.1.3 on 2023-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Оферта'),
        ),
    ]
