# Generated by Django 4.1.3 on 2023-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='last_seats',
            field=models.BooleanField(blank=True, null=True, verbose_name='Последни места'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='new_offer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нова оферта'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sold_out_offer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sold out'),
        ),
    ]
