# Generated by Django 4.1.3 on 2023-08-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_feedback_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_5',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_name_4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_name_5',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_pic_4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_pic_5',
        ),
    ]
