# Generated by Django 4.1.3 on 2023-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_joboffer_last_seats_joboffer_new_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='suitable_for',
            field=models.CharField(blank=True, choices=[('students', 'Студенти'), ('non-students', 'Нестуденти')], max_length=20, null=True, verbose_name='Подходящо за'),
        ),
    ]
