# Generated by Django 4.1.3 on 2023-08-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_joboffer_last_seats_joboffer_new_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Град')),
                ('fact1', models.TextField(blank=True, null=True, verbose_name='Факт 1')),
                ('fact2', models.TextField(blank=True, null=True, verbose_name='Факт 2')),
                ('fact3', models.TextField(blank=True, null=True, verbose_name='Факт 3')),
                ('city_pic', models.ImageField(blank=True, null=True, upload_to='city_pics/', verbose_name='Снимка')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Оферта')),
                ('student_name_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 1')),
                ('student_pic_1', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 1')),
                ('feedback_1', models.TextField(blank=True, null=True, verbose_name='Отзив 1')),
                ('student_name_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 2')),
                ('student_pic_2', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 2')),
                ('feedback_2', models.TextField(blank=True, null=True, verbose_name='Отзив 2')),
                ('student_name_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Студент 3')),
                ('student_pic_3', models.ImageField(blank=True, null=True, upload_to='feedback_student_pics/', verbose_name='Снимка 3')),
                ('feedback_3', models.TextField(blank=True, null=True, verbose_name='Отзив 3')),
            ],
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='interesting',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='students_feedback',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='suitable_for',
            field=models.CharField(blank=True, choices=[('Студенти', 'Студенти'), ('Нестуденти', 'Нестуденти')], max_length=20, null=True, verbose_name='Подходящо за'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='housing',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Housing'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.feedback', to_field='feedback_name'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.city', to_field='name'),
            preserve_default=False,
        ),
    ]
