# Generated by Django 4.1.3 on 2023-08-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_feedback_feedback_4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservices',
            options={'verbose_name': 'Допълнителни услуги', 'verbose_name_plural': 'Допълнителни услуги'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Град', 'verbose_name_plural': 'Градове'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Работодател', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратна връзка', 'verbose_name_plural': 'Обратна връзка'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'Работна оферта', 'verbose_name_plural': 'Работни оферти'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цени'},
        ),
    ]
