# Generated by Django 4.1.3 on 2023-08-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_joboffer_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='suitable_for',
            field=models.CharField(blank=True, choices=[('Студенти', 'Студенти'), ('Нестуденти', 'Нестуденти')], max_length=20, null=True, verbose_name='Подходящо за'),
        ),
    ]
