# Generated by Django 4.1.3 on 2023-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_additionalservices_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='bonus',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='couples',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Подходящо за двойки'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='english_level',
            field=models.CharField(blank=True, choices=[('Ниско', 'Ниско'), ('Средно', 'Средно'), ('Високо', 'Високо')], max_length=10, null=True, verbose_name='Ниво на английски език'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='groups',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Подходящо за групи'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='housing',
            field=models.CharField(blank=True, default='Не', max_length=10, null=True, verbose_name='Housing'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='last_seats',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], max_length=5, null=True, verbose_name='Последни места'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='new_offer',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], max_length=5, null=True, verbose_name='Нова оферта'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='overtime',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Overtime'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='sold_out_offer',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], max_length=5, null=True, verbose_name='Sold out'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='tips',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Бакшиши'),
        ),
    ]
