# Generated by Django 4.1.3 on 2023-08-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_joboffer_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='housing',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], max_length=2, null=True, verbose_name='Housing'),
        ),
    ]
