# Generated by Django 4.1.3 on 2023-09-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='state',
        ),
    ]
