# Generated by Django 4.1.3 on 2023-11-05 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_prices_price_remove_prices_price_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='validity_date_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Валидно до - Ден:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='validity_date_month',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]*$', 'Използвай само главни букви.')], verbose_name='Валидно до - Месец:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='validity_date_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Валидно до - Година:'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='last_seats',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Последни места'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='new_offer',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Нова оферта'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='sold_out_offer',
            field=models.CharField(blank=True, choices=[('True', 'Да'), ('False', 'Не')], default=False, max_length=5, null=True, verbose_name='Sold out'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discounted_premium',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Premium(задраскана):'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discounted_self_arrange',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Self Arranged(задраскана):'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discounted_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Standard(задраскана):'),
        ),
    ]
