# Generated by Django 4.1.3 on 2023-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_joboffer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Най-ранно заминаване'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Най-късно заминаване'),
        ),
    ]
