# Generated by Django 4.1.3 on 2023-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_prices_validity_date_day_prices_validity_date_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='amount_of_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отстъпка до ($):'),
        ),
    ]
