# Generated by Django 4.1.3 on 2023-10-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_joboffer_begin_date_alter_joboffer_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price_description',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='pricing_type',
        ),
        migrations.AddField(
            model_name='prices',
            name='actual_premium',
            field=models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Full Premium:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='actual_self_arrange',
            field=models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Self Arranged:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='actual_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Актуална цена за Full Standard:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='discounted_premium',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена преди отстъпката за Full Premium:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='discounted_self_arrange',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена преди отстъпката за Self Arranged:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='discounted_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена преди отстъпката за Full Standard:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='plane_ticket_highest',
            field=models.FloatField(blank=True, null=True, verbose_name='Самолетен билет - най-висока цена:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='plane_ticket_lowest',
            field=models.FloatField(blank=True, null=True, verbose_name='Самолетен билет - най-ниска цена:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='sevis',
            field=models.FloatField(blank=True, null=True, verbose_name='Такса Sevis:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='sign_up_fees',
            field=models.FloatField(blank=True, null=True, verbose_name='Такса при записване:'),
        ),
        migrations.AddField(
            model_name='prices',
            name='visa_interview',
            field=models.FloatField(blank=True, null=True, verbose_name='Такса визово интервю:'),
        ),
    ]
