# Generated by Django 4.1.3 on 2023-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_prices_price_remove_prices_price_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='discounted_premium',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Premium(задраскана):'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discounted_self_arrange',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Self Arranged(задраскана):'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discounted_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Промо цена за Full Standard(задраскана):'),
        ),
    ]
