# Generated by Django 4.1.3 on 2026-09-29 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_prices_amount_of_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='assignment',
            field=models.BooleanField(default=False, verbose_name='Assignment'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Свободна'), ('last_seats', 'Последни места'), ('occupied', 'Заета')], default='', max_length=20, verbose_name='Реална наличност'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Наличността е обновена на'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sponsor',
            field=models.CharField(blank=True, choices=[('CHI', 'CHI'), ('United', 'United'), ('Dynamic', 'Dynamic'), ('AWA', 'AWA')], default='', max_length=10, verbose_name='Спонсор'),
        ),
        migrations.CreateModel(
            name='OfferLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Име')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Имейл')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('university', models.CharField(max_length=160, verbose_name='Университет')),
                ('course', models.CharField(max_length=40, verbose_name='Курс')),
                ('specialty', models.CharField(max_length=160, verbose_name='Специалност')),
                ('status', models.CharField(choices=[('new', 'Нов потенциал'), ('contacted', 'Потърсен'), ('enrolled', 'Записан студент'), ('closed', 'Затворен')], default='new', max_length=20, verbose_name='CRM статус')),
                ('source', models.CharField(default='Работни оферти', max_length=80, verbose_name='Източник')),
                ('privacy_consent', models.BooleanField(default=True, verbose_name='Съгласие за контакт')),
                ('inquiry_message', models.TextField(blank=True, default='', verbose_name='Запитвания от любими оферти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('favorite_offers', models.ManyToManyField(blank=True, related_name='offer_leads', to='web.joboffer', verbose_name='Любими оферти')),
            ],
            options={
                'verbose_name': 'CRM потенциал от офертите',
                'verbose_name_plural': 'CRM потенциали от офертите',
                'ordering': ('-created_at',),
            },
        ),
    ]
