# Generated by Django 4.1.3 on 2023-11-03 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_prices_validity_date_day_prices_validity_date_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='validity_date_month',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')], verbose_name='Валидно до - Месец:'),
        ),
    ]
