# Generated by Django 4.1.3 on 2023-11-05 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_prices_validity_date_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='validity_date_month',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]*$', 'Използвай само главни букви.')], verbose_name='Валидно до - Месец:'),
        ),
    ]
