# Generated by Django 4.1.3 on 2023-11-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_prices_discounted_premium_and_more'),
        ('web', '0013_alter_prices_validity_date_month'),
    ]

    operations = [
    ]
