# Generated by Django 4.1.3 on 2023-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_merge_20231109_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='amount_of_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отстъпка до:'),
        ),
    ]
