# Generated by Django 4.1.3 on 2023-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_prices_amount_of_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='amount_of_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отстъпка до ($):'),
        ),
    ]
