# Generated by Django 4.1.3 on 2023-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание 1')),
                ('content2', models.TextField(blank=True, null=True, verbose_name='Съдържание 2')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': '"За нас"',
                'verbose_name_plural': '5. Секция "За нас"',
            },
        ),
        migrations.CreateModel(
            name='CallToActionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отгоре')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие основно')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отдолу')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Call to Action',
                'verbose_name_plural': '6. Секция "Call to Action"',
            },
        ),
        migrations.CreateModel(
            name='ForthSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': '4. Четвърти слайдер',
            },
        ),
        migrations.CreateModel(
            name='MainPricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отгоре')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие основно')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отдолу')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Цени',
                'verbose_name_plural': '8. Секция "Цени"',
            },
        ),
        migrations.CreateModel(
            name='MainServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 1')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание 1')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 2')),
                ('content2', models.TextField(blank=True, null=True, verbose_name='Съдържание 2')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 3')),
                ('content3', models.TextField(blank=True, null=True, verbose_name='Съдържание 3')),
                ('title4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 4')),
                ('content4', models.TextField(blank=True, null=True, verbose_name='Съдържание 4')),
                ('title5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 5')),
                ('content5', models.TextField(blank=True, null=True, verbose_name='Съдържание 5')),
                ('title6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 6')),
                ('content6', models.TextField(blank=True, null=True, verbose_name='Съдържание 6')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': '9. Секция "Услуги"',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': '1. Основен слайдер',
            },
        ),
        migrations.CreateModel(
            name='SecondSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие')),
                ('content1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Съдържание')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': '2. Втори слайдер',
            },
        ),
        migrations.CreateModel(
            name='ThirdSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': '3. Трети слайдер',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.URLField(blank=True, null=True, verbose_name='Основно видео')),
                ('main_video_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица')),
                ('video_1', models.URLField(blank=True, null=True, verbose_name='Видео 1')),
                ('video_1_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 1')),
                ('video_2', models.URLField(blank=True, null=True, verbose_name='Видео 2')),
                ('video_2_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 2')),
                ('video_3', models.URLField(blank=True, null=True, verbose_name='Видео 3')),
                ('video_3_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 3')),
                ('video_4', models.URLField(blank=True, null=True, verbose_name='Видео 4')),
                ('video_4_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 4')),
                ('video_5', models.URLField(blank=True, null=True, verbose_name='Видео 5')),
                ('video_5_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 5')),
                ('button_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': '7. Секция "Видеа"',
            },
        ),
    ]
