# Generated by Django 4.1.3 on 2023-11-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainslider',
            old_name='title',
            new_name='title1',
        ),
    ]
