# Generated by Django 4.1.3 on 2023-11-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondslider',
            name='content2',
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='content1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Съдържание'),
        ),
    ]
