# Generated by Django 4.1.3 on 2023-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_title_mainslider_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallToActionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ForthSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainPricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('title3', models.CharField(max_length=255)),
                ('content3', models.TextField()),
                ('title4', models.CharField(max_length=255)),
                ('content4', models.TextField()),
                ('title5', models.CharField(max_length=255)),
                ('content5', models.TextField()),
                ('title6', models.CharField(max_length=255)),
                ('content6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.URLField(blank=True, null=True, verbose_name='Основно видео')),
                ('main_video_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица')),
                ('video_1', models.URLField(blank=True, null=True, verbose_name='Видео 1')),
                ('video_1_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 1')),
                ('video_2', models.URLField(blank=True, null=True, verbose_name='Видео 2')),
                ('video_2_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 2')),
                ('video_3', models.URLField(blank=True, null=True, verbose_name='Видео 3')),
                ('video_3_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 3')),
                ('video_4', models.URLField(blank=True, null=True, verbose_name='Видео 4')),
                ('video_4_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 4')),
                ('video_5', models.URLField(blank=True, null=True, verbose_name='Видео 5')),
                ('video_5_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 5')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеа - Начална страница',
            },
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_link',
            field=models.CharField(default='value', max_length=255),
            preserve_default=False,
        ),
    ]
