# Generated by Django 4.1.3 on 2023-11-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_aboutsection_calltoactionsection_forthslider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
