# Generated by Django 4.1.3 on 2023-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.URLField(blank=True, null=True, verbose_name='Основно видео')),
                ('main_video_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица')),
                ('video_1', models.URLField(blank=True, null=True, verbose_name='Видео 1')),
                ('video_1_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 1')),
                ('video_2', models.URLField(blank=True, null=True, verbose_name='Видео 2')),
                ('video_2_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 2')),
                ('video_3', models.URLField(blank=True, null=True, verbose_name='Видео 3')),
                ('video_3_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 3')),
                ('video_4', models.URLField(blank=True, null=True, verbose_name='Видео 4')),
                ('video_4_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 4')),
                ('video_5', models.URLField(blank=True, null=True, verbose_name='Видео 5')),
                ('video_5_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 5')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеа - Начална страница',
            },
        ),
    ]
