# Generated by Django 4.1.3 on 2023-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='calltoactionsection',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='forthslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='mainpricingsection',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='secondslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='secondslider',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие'),
        ),
        migrations.AddField(
            model_name='thirdslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AddField(
            model_name='video',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AddField(
            model_name='video',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бутон - текст'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 1'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 2'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='calltoactionsection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='calltoactionsection',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='calltoactionsection',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отгоре'),
        ),
        migrations.AlterField(
            model_name='calltoactionsection',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие основно'),
        ),
        migrations.AlterField(
            model_name='calltoactionsection',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отдолу'),
        ),
        migrations.AlterField(
            model_name='forthslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='forthslider',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='forthslider',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие'),
        ),
        migrations.AlterField(
            model_name='forthslider',
            name='top_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие'),
        ),
        migrations.AlterField(
            model_name='mainpricingsection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='mainpricingsection',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='mainpricingsection',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отгоре'),
        ),
        migrations.AlterField(
            model_name='mainpricingsection',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие основно'),
        ),
        migrations.AlterField(
            model_name='mainpricingsection',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие отдолу'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 1'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 2'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content3',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 3'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content4',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 4'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content5',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 5'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='content6',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание 6'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 1'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 2'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 3'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 4'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 5'),
        ),
        migrations.AlterField(
            model_name='mainservicessection',
            name='title6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие 6'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие'),
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='content1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Съдържание - първи ред'),
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='content2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Съдържание - втори ред'),
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие'),
        ),
        migrations.AlterField(
            model_name='thirdslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бутон - линк'),
        ),
        migrations.AlterField(
            model_name='thirdslider',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='thirdslider',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Голямо заглавие'),
        ),
        migrations.AlterField(
            model_name='thirdslider',
            name='top_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Малко заглавие'),
        ),
    ]
