# Generated by Django 4.1.3 on 2023-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_aboutsection_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': '"За нас"', 'verbose_name_plural': '5. Секция "За нас"'},
        ),
        migrations.AlterModelOptions(
            name='calltoactionsection',
            options={'verbose_name': 'Call to Action', 'verbose_name_plural': '6. Секция "Call to Action"'},
        ),
        migrations.AlterModelOptions(
            name='forthslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': '4. Четвърти слайдер'},
        ),
        migrations.AlterModelOptions(
            name='mainpricingsection',
            options={'verbose_name': 'Цени', 'verbose_name_plural': '8. Секция "Цени"'},
        ),
        migrations.AlterModelOptions(
            name='mainservicessection',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': '9. Секция "Услуги"'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': '1. Основен слайдер'},
        ),
        migrations.AlterModelOptions(
            name='secondslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': '2. Втори слайдер'},
        ),
        migrations.AlterModelOptions(
            name='thirdslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': '3. Трети слайдер'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': '7. Секция "Видеа"'},
        ),
        migrations.RemoveField(
            model_name='secondslider',
            name='content2',
        ),
        migrations.AlterField(
            model_name='secondslider',
            name='content1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Съдържание'),
        ),
    ]
