# Generated by Django 4.1.3 on 2023-06-15 21:55

import aimtravel_site.user_profile.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_first_name', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Име')),
                ('employee_last_name', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Фамилия')),
                ('employee_role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Позиция')),
                ('employee_pic', models.URLField(blank=True, default='https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o=', null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_digits])),
                ('employee_email', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Име')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Презиме')),
                ('last_name', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Фамилия')),
                ('bg_personal_number', models.CharField(blank=True, max_length=10, null=True, validators=[aimtravel_site.user_profile.validators.only_digits], verbose_name='ЕГН')),
                ('date_of_birth', models.DateField(blank=True, help_text='dd-mm-yyyy', null=True, verbose_name='Дата на раждане')),
                ('place_of_birth', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Място на раждане')),
                ('city', models.CharField(blank=True, max_length=15, null=True, verbose_name='Град')),
                ('province', models.CharField(blank=True, max_length=15, null=True, verbose_name='Област')),
                ('street', models.CharField(blank=True, max_length=30, null=True, verbose_name='Улица/ж.к.')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Националност')),
                ('family_status', models.CharField(blank=True, max_length=10, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Семеен статус')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_digits], verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Контакт за спешни случаи')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон')),
                ('emergency_contact_email', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=15, null=True, verbose_name='Връзка')),
                ('university', models.CharField(blank=True, max_length=40, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Университет')),
                ('major_study', models.CharField(blank=True, max_length=50, null=True, verbose_name='Специалност')),
                ('year_of_education', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Курс')),
                ('is_fulltime_student', models.BooleanField(blank=True, null=True, verbose_name='Студент "Редовно обучение"')),
                ('possible_begin_date', models.DateField(blank=True, null=True, verbose_name='Дата на започване')),
                ('possible_finish_date', models.DateField(blank=True, null=True, verbose_name='Дата на приключване')),
                ('is_wat_before', models.BooleanField(blank=True, null=True, verbose_name='Участвал ли си в WAT преди?')),
                ('wat_before_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ако да, коя година')),
                ('position_held1', models.CharField(blank=True, max_length=30, null=True)),
                ('position_period1', models.CharField(blank=True, max_length=25, null=True)),
                ('employer_name1', models.CharField(blank=True, max_length=30, null=True)),
                ('employer_city1', models.CharField(blank=True, max_length=30, null=True)),
                ('position_held2', models.CharField(blank=True, max_length=30, null=True)),
                ('position_period2', models.CharField(blank=True, max_length=25, null=True)),
                ('employer_name2', models.CharField(blank=True, max_length=30, null=True)),
                ('employer_city2', models.CharField(blank=True, max_length=30, null=True)),
                ('visa_before', models.BooleanField(blank=True, null=True)),
                ('visa_before_year', models.CharField(blank=True, max_length=4, null=True)),
                ('issued_visa_before', models.BooleanField(blank=True, null=True)),
                ('issued_visa_before_type', models.CharField(blank=True, max_length=4, null=True)),
                ('purpose_of_visit', models.CharField(blank=True, max_length=20, null=True)),
                ('any_relatives_in_USA', models.BooleanField(blank=True, null=True)),
                ('relatives_kind', models.CharField(blank=True, max_length=20, null=True)),
                ('knowledge_of_english', models.CharField(blank=True, max_length=10, null=True)),
                ('other_language', models.CharField(blank=True, max_length=20, null=True)),
                ('other_language_level', models.CharField(blank=True, max_length=10, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('personal_qualities', models.TextField(blank=True, null=True)),
                ('id_passport_number', models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_site.user_profile.validators.only_digits], verbose_name='Номер на паспорт')),
                ('passport_date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата на издаване')),
                ('is_received_visa', models.BooleanField(blank=True, null=True, verbose_name='Получена виза')),
                ('foreign_university', models.CharField(blank=True, max_length=40, null=True, validators=[aimtravel_site.user_profile.validators.only_letters], verbose_name='Чуждестранен университет')),
                ('search_job_pref', models.CharField(blank=True, max_length=15, null=True, verbose_name='Предпочитана работа')),
                ('how_to_reach', models.CharField(blank=True, max_length=15, null=True, verbose_name='Как да комуникираме?')),
                ('visa_photo', models.URLField(blank=True, default='https://cdn5.vectorstock.com/i/1000x1000/54/34/a-student-boy-cartoon-character-isolated-on-white-vector-36115434.jpg', null=True, verbose_name='Снимка за ВИЗА')),
                ('file_field', models.FileField(blank=True, null=True, upload_to='files/%Y-%m-%d')),
            ],
        ),
    ]
