# Generated by Django 4.1.3 on 2024-09-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_pic',
        ),
        migrations.AlterField(
            model_name='students',
            name='visa_photo',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to='students/student_pic/', verbose_name='Снимка за виза'),
        ),
    ]
