# Generated by Django 4.1.3 on 2024-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_employee_employee_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_pic',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to='profile/employee_pic/', verbose_name='служебна снимка'),
        ),
    ]
