# Generated by Django 4.1.3 on 2024-01-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_employee_employee_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='visa_photo',
        ),
    ]
