# Generated by Django 4.1.3 on 2024-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_students_visa_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='visa_photo',
            field=models.FileField(blank=True, default='profile/default_profile_pic.jpg', null=True, upload_to='students/student_pic/', verbose_name='Снимка за виза'),
        ),
    ]
