# Generated by Django 4.1.3 on 2024-01-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_students_visa_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_pic',
        ),
    ]
