# Generated by Django 4.1.3 on 2026-09-11 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField()),
                ('egn', models.CharField(max_length=10)),
                ('id_card_number', models.CharField(max_length=9)),
                ('place_of_birth', models.CharField(max_length=80)),
                ('university', models.CharField(max_length=160)),
                ('major', models.CharField(max_length=120)),
                ('year_of_study', models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('master', 'Магистратура')], max_length=8)),
                ('program_option', models.CharField(choices=[('full_arranged', 'FULL ARRANGED'), ('self_arranged', 'SELF ARRANGED')], max_length=16)),
                ('season', models.PositiveSmallIntegerField()),
                ('office', models.CharField(choices=[('varna', 'Варна'), ('sofia', 'София')], max_length=8)),
                ('accepted_terms_at', models.DateTimeField()),
                ('declared_truth_at', models.DateTimeField()),
                ('accepted_gdpr_at', models.DateTimeField()),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True)),
                ('contract_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('contract_issued', 'Договорът е издаден'), ('contract_failed', 'Договорът не се генерира'), ('email_failed', 'Имейлът не тръгна'), ('cancelled', 'Отказана')], default='contract_issued', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('draft_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('varna', 'Варна'), ('sofia', 'София')], max_length=8)),
                ('season', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='contracts/%Y/%m/')),
                ('docx', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_document', to='apply.application')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contractcounter',
            constraint=models.UniqueConstraint(fields=('office', 'season'), name='uniq_counter_office_season'),
        ),
        migrations.AddIndex(
            model_name='applicationdraft',
            index=models.Index(fields=['updated_at'], name='apply_appli_updated_19e602_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='apply_appli_email_c0bf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['office', 'season'], name='apply_appli_office_17e3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='apply_appli_created_066d59_idx'),
        ),
    ]
