# Generated by Django 4.1.3 on 2026-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='egn',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
