# Generated by Django 4.1.3 on 2023-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Въпрос')),
                ('faq_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отговор')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='MainFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_1_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_1_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_1_image', models.ImageField(blank=True, null=True, upload_to='main_feedback_pics/', verbose_name='Снимка')),
            ],
            options={
                'verbose_name': 'Истории на студенти',
                'verbose_name_plural': 'Истории на студенти',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('news_content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('news_url', models.URLField(blank=True, null=True, verbose_name='Линк към Facebook/Instagram')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_pics/', verbose_name='Снимка')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
