# Generated by Django 4.1.3 on 2023-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('news_content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('news_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
