# Generated by Django 4.1.3 on 2023-02-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('post_content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
            ],
        ),
    ]
