# Generated by Django 4.1.3 on 2023-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_1_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_1_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_1_image', models.URLField(blank=True, null=True)),
                ('feedback_2_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_2_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_2_image', models.URLField(blank=True, null=True)),
                ('feedback_3_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_3_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_3_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback допълнителна страница',
                'verbose_name_plural': 'Feedback допълнителна страница',
            },
        ),
        migrations.CreateModel(
            name='MainFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_1_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_1_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_1_image', models.URLField(blank=True, null=True)),
                ('feedback_2_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_2_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_2_image', models.URLField(blank=True, null=True)),
                ('feedback_3_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заглавие')),
                ('feedback_3_content', models.TextField(blank=True, null=True, verbose_name='Съдържание')),
                ('feedback_3_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback Начална страница',
                'verbose_name_plural': 'Feedback Начална страница',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новини', 'verbose_name_plural': 'Новини'},
        ),
    ]
