# Generated by Django 4.1.3 on 2023-02-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='post_content',
            new_name='news_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='post_title',
            new_name='news_title',
        ),
    ]
