# Generated by Django 4.1.3 on 2023-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_additionalfeedback_mainfeedback_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfeedback',
            name='feedback_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_feedback_pics/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='mainfeedback',
            name='feedback_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_feedback_pics/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='mainfeedback',
            name='feedback_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_feedback_pics/', verbose_name='Снимка'),
        ),
    ]
