# Generated by Django 4.1.3 on 2025-11-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
