# Generated by Django 4.1.3 on 2023-02-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_rename_post_content_news_news_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
