# Generated by Django 4.1.3 on 2023-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_additionalfeedback_mainfeedback_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.URLField(blank=True, null=True, verbose_name='Основно видео')),
                ('main_video_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица')),
                ('video_1', models.URLField(blank=True, null=True, verbose_name='Видео 1')),
                ('video_1_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 1')),
                ('video_2', models.URLField(blank=True, null=True, verbose_name='Видео 2')),
                ('video_2_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 2')),
                ('video_3', models.URLField(blank=True, null=True, verbose_name='Видео 3')),
                ('video_3_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 3')),
                ('video_4', models.URLField(blank=True, null=True, verbose_name='Видео 4')),
                ('video_4_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 4')),
                ('video_5', models.URLField(blank=True, null=True, verbose_name='Видео 5')),
                ('video_5_image', models.ImageField(blank=True, null=True, upload_to='video_pics/', verbose_name='Корица 5')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеа - Начална страница',
            },
        ),
        migrations.AlterModelOptions(
            name='additionalfeedback',
            options={'verbose_name': 'Отзиви от студенти', 'verbose_name_plural': 'Отзиви от студенти'},
        ),
        migrations.AlterModelOptions(
            name='mainfeedback',
            options={'verbose_name': 'Истории на студенти', 'verbose_name_plural': 'Истории на студенти'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.URLField(blank=True, null=True, verbose_name='Линк към Facebook/Instagram'),
        ),
    ]
