# Generated by Django 4.1.3 on 2023-08-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_alter_mainfeedback_feedback_1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeedback',
            name='feedback_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_feedback_pics/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='additionalfeedback',
            name='feedback_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_feedback_pics/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='additionalfeedback',
            name='feedback_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_feedback_pics/', verbose_name='Снимка'),
        ),
    ]
