# Generated by Django 4.1.3 on 2023-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_video_alter_additionalfeedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Въпрос')),
                ('faq_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отговор')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
