# Generated by Django 4.1.3 on 2023-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_alter_additionalfeedback_feedback_1_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalfeedback',
            options={'verbose_name': 'Отзиви от студенти', 'verbose_name_plural': 'Отзиви от студенти'},
        ),
        migrations.AlterModelOptions(
            name='mainfeedback',
            options={'verbose_name': 'Истории на студенти', 'verbose_name_plural': 'Истории на студенти'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.URLField(blank=True, null=True, verbose_name='Линк към Facebook/Instagram'),
        ),
    ]
