# Generated by Django 4.1.3 on 2023-11-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_delete_additionalfeedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
