# Generated by Django 4.1.3 on 2025-11-07 21:34

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
