# Generated by Django 4.1.3 on 2023-09-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_alter_news_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalFeedback',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_2_content',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_2_image',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_2_title',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_3_content',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_3_image',
        ),
        migrations.RemoveField(
            model_name='mainfeedback',
            name='feedback_3_title',
        ),
    ]
