# Generated by Django 4.1.3 on 2023-11-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_delete_additionalfeedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
